version: '3'
services:
  app:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./:/app/
    restart: always
    tty: true
    stdin_open: true
    command: sh -c "npm run dev"
    environment:
      - WATCHPACK_POLLING=true
